# Site settings

title: Program Butler
description: A resume about Lee Ji Hoon

# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings

username: Lee Ji Hoon
user_description: 인공지능을 활용한 서비스에 관심이 많습니다.
user_title: AI Developer
email: monaminino@gmail.com
#twitter_username: lorem_ipsum
github_username:  Program-Butler
gplus_username:  monaminino


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
